//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.09.11 at 10:02:07 PM BST 
//


package com.netthreads.mavenize.model.mapping;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{}dependency"/>
 *           &lt;element ref="{}dependency-source"/>
 *         &lt;/choice>
 *         &lt;element ref="{}dependency-target"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dependency",
    "dependencySource",
    "dependencyTarget"
})
@XmlRootElement(name = "mapping")
public class Mapping {

    protected Dependency dependency;
    @XmlElement(name = "dependency-source")
    protected DependencySource dependencySource;
    @XmlElement(name = "dependency-target", required = true)
    protected DependencyTarget dependencyTarget;

    /**
     * Gets the value of the dependency property.
     * 
     * @return
     *     possible object is
     *     {@link Dependency }
     *     
     */
    public Dependency getDependency() {
        return dependency;
    }

    /**
     * Sets the value of the dependency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dependency }
     *     
     */
    public void setDependency(Dependency value) {
        this.dependency = value;
    }

    /**
     * Gets the value of the dependencySource property.
     * 
     * @return
     *     possible object is
     *     {@link DependencySource }
     *     
     */
    public DependencySource getDependencySource() {
        return dependencySource;
    }

    /**
     * Sets the value of the dependencySource property.
     * 
     * @param value
     *     allowed object is
     *     {@link DependencySource }
     *     
     */
    public void setDependencySource(DependencySource value) {
        this.dependencySource = value;
    }

    /**
     * Gets the value of the dependencyTarget property.
     * 
     * @return
     *     possible object is
     *     {@link DependencyTarget }
     *     
     */
    public DependencyTarget getDependencyTarget() {
        return dependencyTarget;
    }

    /**
     * Sets the value of the dependencyTarget property.
     * 
     * @param value
     *     allowed object is
     *     {@link DependencyTarget }
     *     
     */
    public void setDependencyTarget(DependencyTarget value) {
        this.dependencyTarget = value;
    }

}
